# 🔗 Links:
# Source file: https://github.com/obytes/react-native-template-obytes/blob/master/.github/actions/setup-node-bun-install/action.yml
# Composite actions docs: https://docs.github.com/en/actions/creating-actions/creating-a-composite-action

# ✍️ Description:
# This is a composite action, which means it can be used in other actions.
# It is used in almost all workflows to set up the environment and install dependencies.
# Updating  the package manager or Node version here will be reflected in all workflows.

# 👀 Example usage:
#       - name : 📦 Setup Node + bun + install deps
#         uses: ./.github/actions/setup-node-bun-install

name: 'Setup  Node + bun + Install Dependencies'
description: 'Setup  Node + bun + Install Dependencies'
runs:
  using: 'composite'
  steps:
    - uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest

    - uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: 📦 Install Project Dependencies
      run: bun install --frozen-lockfile
      shell: bash
